#!/usr/bin/env python

import sys
import os
from builder.bootstrap import setup, get_hdist_config_filename

root_dir = os.path.dirname(__file__)
setup(root_dir)

from hashdist.cli.main import help_on_exceptions, main
from hashdist.hdist_logging import Logger, DEBUG

logger = Logger(DEBUG)

sys.exit(help_on_exceptions(logger, main, sys.argv, os.environ, logger,
                            default_config_filename=get_hdist_config_filename()))
