export PYTHON_HPCMP_ARCH=linux
export PYTHON_HPCMP=$HOME/src/python-hpcmp
export PYTHON_HPCMP_PREFIX=$PYTHON_HPCMP/$PYTHON_HPCMP_ARCH
export PYTHON_HPCMP_PYTHON=$PYTHON_HPCMP_PREFIX/bin/python
export PETSC_DIR=$PYTHON_HPCMP/petsc
export PETSC_ARCH=$PYTHON_HPCMP_ARCH
