#!/usr/bin/env python
import os
import sys

from builder.bootstrap import setup, get_hdist_config_filename
setup(os.path.dirname(__file__))

from builder.builder import main
sys.exit(main(get_hdist_config_filename()))
