export PYTHONHPC_ARCH=linux
export PYTHONHPC_PREFIX=${PYTHONHPC}/${PYTHONHPC_ARCH}
export PYTHONHPC_PYTHON=${PYTHONHPC_PREFIX}/bin/python
export PATH=${PYTHONHPC_PREFIX}/bin:${PATH}
export LD_LIBRARY_PATH=${PYTHONHPC_PREFIX}/lib
export DYLD_LIBRARY_PATH=${PYTHONHPC_PREFIX}/lib
